Clients -->

###
GET http://localhost:3000/api/Clients
Content-Type: application/json

{
    "nombre": "Mario",
    "apellidos": "Vaquerizo",
    "direccion": "Calle Viyuela",
    "telefono": "955555555",
    "email": "client@client.com",
    "fecha_nacimiento": "1936-03-15",
    "dni": "56743234Y"
}

###
PUT http://localhost:3000/api/Clients/2

Content-Type: application/json

{
    "nombre": "Mario",
    "apellidos": "Conde",
    "direccion": "Calle del destrozo, 5",
    "telefono": "696969692",
    "email": "client2@client.com",
    "fecha_nacimiento": "1959-06-12",
    "dni": "56744534Y"
}

###
DELETE http://localhost:3000/api/Clients/2


###
POST http://localhost:3000/api/Clients/new/78
Content-Type: application/json

{
    "nombre": "Pepe",
    "apellidos": "Viyuela", 
    "direccion": "c olvido 10", 
    "telefono": 666666666, 
    "fecha_nacimiento": "1980-03-10", 
    "dni": "99999999x", 
    "email": "pepeviyuela@gmail.com"
}

Hotels -->

###
GET http://localhost:3000/api/hoteles

###
POST http://localhost:3000/api/hotels/new
Content-Type: application/json

{
    "nombre": "Hostal el torero",
    "direccion": "C Rosa Benito", 
    "ciudad": "Sevilla", "num_estrellas": 1, 
    "descripcion": "Huele a rata", 
    "tarifa": 300
}

###
PUT http://localhost:3000/api/hotels/edit/1
Content-Type: application/json

{
    "nombre": "Hotel perplejo",
    "direccion": "Calle Jesus Gil", 
    "ciudad": "Madrid", 
    "num_estrellas": 5, 
    "descripcion": "No ponen toallas en el baño", 
    "tarifa": 25
}

###
DELETE http://localhost:3000/api/hotels/delete/1

Travels -->

###
GET http://localhost:3000/api/travels

###
POST http://localhost:3000/api/travels/new/3
Content-Type: application/json

{
    "fecha_salida": "03-10-2019",
    "fecha_vuelta": "05-03-2019", 
    "id_vuelo_ida": "43564365GFH4765467", 
    "id_vuelo_vuelta": "45654HGF6757876", 
    "hotel": "Hostal el torero"
}

###
PUT http://localhost:3000/api/travels/edit/2 
Content-Type: application/json

{
    "fecha_salida": "02-10-2019",
    "fecha_vuelta": "06-03-2019", 
    "id_vuelo_ida": "65756HGFH7567", 
    "id_vuelo_vuelta": "456756GHF77657", 
    "hotel": "Hostal el torero"
}

###
DELETE http://localhost:3000/api/travels/delete/3

Travels/Clients -->

###
POST http://localhost:3000/api/client/3/travel/2

